apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-service-set
spec:
  selector:
    matchLabels:
      app: auth-service
  serviceName: "auth-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: yogson/dzcontainers:auth_service
        imagePullPolicy: Always
        env:
          - name: USER_DATA_STORE
            value: "/data/user_data"
          - name: USERS_STORE
            value: "/data/users"
        volumeMounts:
        - mountPath: "/data"
          name: pvc
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage